name: vkd3d-proton-mingw

on:
  workflow_dispatch:
  push:
    branches:
     - master
    paths:
     - 'public/vkd3d-proton-mingw/.SRCINFO'

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Makepkg Build and Check
      id: makepkg
      uses: edlanglois/pkgbuild-action@v1
      with:
        pkgdir: "public/vkd3d-proton-mingw"
        aurDeps: 1
    - name: Print Package Files
      run: |
        echo "Successfully created the following package archive"
        echo "Package: ${{ steps.makepkg.outputs.pkgfile0 }}"
    - uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{secrets.GITHUB_TOKEN}}
        tag: packages
        file: ${{ steps.makepkg.outputs.pkgfile0 }}
        overwrite: true
